/* Generated By:JJTree: Do not edit this line. ASTedge_stmt.java */

package dotparser;

public class ASTedge_stmt extends SimpleNode {
  public ASTedge_stmt(int id) {
    super(id);
  }

  public ASTedge_stmt(DOTParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DOTParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
